branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/ # regex

language: android
sudo: false

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-26.0.1
    - android-19
    - android-21
    - android-22
    - android-23
    - android-26

before_install:
    - pip install --user codecov

script:
  - ./gradlew clean testDebugUnitTest jacocoTestReport

after_success:
  - ./gradlew coveralls
  - codecov
  - ./scripts/publish_snapshot.sh

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    tags: true
