branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/ # regex

language: android
sudo: false

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.0
    - android-27
    - doc-27

before_install:
    - pip install --user codecov

script:
  - ./gradlew clean testDebugUnitTest jacocoTestReport

after_success:
  - ./gradlew coveralls
  - codecov
  - ./scripts/publish_snapshot.sh

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    tags: true
