branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/ # regex

language: android
sudo: false

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.0
    - doc-27
    - android-27
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-27

before_install:
    - yes | sdkmanager "platforms;android-27"
    - pip install --user codecov

script:
  - ./gradlew clean testDebugUnitTest jacocoTestReport --info

after_success:
  - ./gradlew coveralls
  - codecov
  - ./scripts/publish_snapshot.sh

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository
env:
  matrix:
  - API=android-27 ABI=armeabi-v7a
  global:
  - ADB_INSTALL_TIMEOUT=8

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: wiaio/wia-android-sdk
    condition: "$API = android-27"
